### ISSUE TITLE
Problem with flash objects and NoScript

### ISSUE THREAD

**Issue by famo** [satyr/lmnpop#1]
Hello satyr,
thanks a lot for your Add-On I really like it.

I tried to use it on YouTube, but I ouldn't manage to open a video in the pop-up window.
I use NoScript to block flash-objects, so in order to play them I need to click on them first - which works totally fine, I can also middle-click and open them in a new tab or window (only the flash-object).
But when I tried with you add-on (right click on object -> lmnpop - Pop Link Location), I only get a blank pop-up.

Could you take a look at this?
Thanks

PS:
See also these screenshots:
http://dl.dropbox.com/u/4551608/youtube.png
http://dl.dropbox.com/u/4551608/youtube-pop.png

**Comment by satyr** [comment]
Try disabling NoScript.

**Comment by famo** [comment]
I can't in the pop-up window is no menu.

Or do you mean in Firefox? This is no solution, I need it.

2012/1/25 Satoshi Murakami
reply@reply.github.com:

**Comment by satyr** [comment]
"Pop Link Location" won't work since NoScript will forbidden it precisely.

Either:
- allowing the video site (_ytimg.com_ for YouTube)
- "Temporarily allow"ing specific videos

worked for me.

**Comment by famo** [comment]
Ah, you use NoScript, too?
What do you mean by:

> Pop Link Location" won't work since NoScript will forbidden it precisely.

NoScript blocks the Pop Link? Maybe it can be turned off in the
NoScript options?

The temporiry allowing, works but it's some extra click so it would be
more nice if it would work out of the box ...

Thanks!
famo

2012/1/25 Satoshi Murakami
reply@reply.github.com:

**Comment by satyr** [comment]
> NoScript blocks the Pop Link?

The popped element will still refer to the same video, which will be blocked by NoScript.

> The temporiry allowing, works but it's some extra click so it would be
> more nice if it would work out of the box ...

You can also permanently allow (whitelist) videos from specific domains. Simply choose "Allow ytimg.com" from NoScript context menu.

**Comment by famo** [comment]
Thanks, I tried this and it works fine on youtube.com.

However I could not get this to work on, kongregate - here for example:
http://www.kongregate.com/games/Djugan/hands-of-war-tower-defense

I allowed:
kongregate.com
and
flash@chat.kongregate.com

If I pop the DIV with the game or the object itself the window is blank.

2012/1/25 Satoshi Murakami:

> > NoScript blocks the Pop Link?
> 
> The popped element will still refer to the same video, which will be blocked by NoScript.
> 
> > The temporiry allowing, works but it's some extra click so it would be
> > more nice if it would work out of the box ...
> 
> You can also permanently allow (whitelist) videos from specific domains. Simply choose "Allow ytimg.com" from NoScript context menu.

**Comment by satyr** [comment]
> However I could not get this to work on, kongregate - here for example:
> http://www.kongregate.com/games/Djugan/hands-of-war-tower-defense

Allowing _kongregate.com_ and popping _gamediv_ worked for me.

Anyway, closing this since it's more like how to use NoScript than an lmnpop issue.
