### ISSUE TITLE
Doesn't work anymore with Firefox 12

### ISSUE THREAD

**Issue by famo** [satyr/lmnpop#2]
Hello,
I cannot "pop" anything with this extension, since my update to Fx 12.
Could you please take a look?

Thanks!

**Comment by satyr** [comment]
Hmm, working for me on OS X 10.6.8.

What OS are you on? Any relevant errors in Error Console?

**Comment by famo** [comment]
I use Windows XP. There are no errors or warnings in the error console.

The highlighting (the red dotted line) still works on right click. However the windows is always blank, whether its an element a link, etc.

**Comment by satyr** [comment]
https://addons.mozilla.org/firefox/downloads/file/151430/lmnpop-20120518-fx.xpi

How about this one?

**Comment by famo** [comment]
Thanks, with this it works again!
